services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: snoremd-dynamodb
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    networks:
      - snoremd-network

networks:
  snoremd-network:
    name: snoremd-network
    driver: bridge
